//HintName: ToolsCtx.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS8019 // Unnecessary using directive
#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)

using global::System;
using global::System.Collections.Generic;
using global::System.Reflection;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::Microsoft.Extensions.AI;
using global::Microsoft.Extensions.DependencyInjection;

namespace Sample
{
    public partial class ToolsCtx
    {
        /// <summary>Gets the default singleton instance of this tool context.</summary>
        public static ToolsCtx Default { get; } = new ToolsCtx();

        /// <inheritdoc />
        public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> GetTools(global::System.IServiceProvider serviceProvider)
        {
            return new global::Microsoft.Extensions.AI.AITool[]
            {
                new Svc_Do_Tool(serviceProvider),
            };
        }

        /// <inheritdoc />
        public override void RegisterTools(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            services.AddSingleton<global::Microsoft.Extensions.AI.AITool>(static sp => new Svc_Do_Tool(sp));
        }

        /// <inheritdoc />
        public override void RegisterTools(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, string key)
        {
            services.AddKeyedSingleton<global::Microsoft.Extensions.AI.AITool>(key, static (sp, _) => new Svc_Do_Tool(sp));
        }

        private sealed class Svc_Do_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private readonly global::System.IServiceProvider? _fallback;
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public Svc_Do_Tool(global::System.IServiceProvider? fallback = null)
            {
                _fallback = fallback;
            }

            public override string Name => "Do";
            public override string Description => string.Empty;
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Reflection.MethodInfo GetTargetMethod()
            {
                var serviceType = typeof(global::Sample.Svc);
                var paramTypes = new global::System.Type[] { typeof(string), typeof(global::Sample.ICache), };
                return serviceType.GetMethod("Do", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, paramTypes, null)
                    ?? throw new global::System.InvalidOperationException("Could not locate target method global::Sample.Svc.Do.");
            }

            private static readonly global::System.Collections.Generic.HashSet<string> s_schemaExcludedParameters = new()
            {
                "cache",
            };

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var inferenceOptions = new global::Microsoft.Extensions.AI.AIJsonSchemaCreateOptions
                {
                    IncludeParameter = static p => !s_schemaExcludedParameters.Contains(p.Name!),
                };
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateFunctionJsonSchema(
                    GetTargetMethod(), title: string.Empty, description: string.Empty, inferenceOptions: inferenceOptions);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string));
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = global::Microsoft.Maui.AI.Attributes.AIToolContext.Helpers.RequireServices(arguments, _fallback);
                var __service = __provider.GetRequiredService<global::Sample.Svc>();
                var __arg_name = global::Microsoft.Maui.AI.Attributes.AIToolContext.Helpers.GetRequiredArg<string>(arguments, "name");
                var __arg_cache = __provider.GetRequiredKeyedService<global::Sample.ICache>(null);
                var __result = __service.Do(__arg_name, __arg_cache);
                return __result;
            }
        }

    }
}
