//HintName: DangerousTools.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS8019 // Unnecessary using directive
#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)

using global::System;
using global::System.Collections.Generic;
using global::System.Reflection;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::Microsoft.Extensions.AI;
using global::Microsoft.Extensions.DependencyInjection;

namespace Sample
{
    public partial class DangerousTools
    {
        /// <summary>Gets the default singleton instance of this tool context.</summary>
        public static DangerousTools Default { get; } = new DangerousTools();

        /// <inheritdoc />
        public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> Tools
        {
            get
            {
                return new global::Microsoft.Extensions.AI.AITool[]
                {
                    new IDangerousService_Read_Tool(),
                    new global::Microsoft.Extensions.AI.ApprovalRequiredAIFunction(new IDangerousService_Write_Tool()),
                };
            }
        }

        private sealed class IDangerousService_Read_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "safe_read";
            public override string Description => "Safe operation.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Reflection.MethodInfo GetTargetMethod()
            {
                var serviceType = typeof(global::Sample.IDangerousService);
                var paramTypes = new global::System.Type[] { };
                return serviceType.GetMethod("Read", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, paramTypes, null)
                    ?? throw new global::System.InvalidOperationException("Could not locate target method global::Sample.IDangerousService.Read.");
            }

            private static readonly global::System.Collections.Generic.HashSet<string> s_schemaExcludedParameters = new()
            {
            };

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var inferenceOptions = new global::Microsoft.Extensions.AI.AIJsonSchemaCreateOptions
                {
                    IncludeParameter = static p => !s_schemaExcludedParameters.Contains(p.Name!),
                };
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateFunctionJsonSchema(
                    GetTargetMethod(), title: string.Empty, description: string.Empty, inferenceOptions: inferenceOptions);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string));
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = global::Microsoft.Maui.AI.Attributes.AIToolContext.Helpers.RequireServices(arguments);
                var __service = __provider.GetRequiredService<global::Sample.IDangerousService>();
                var __result = __service.Read();
                return __result;
            }
        }

        private sealed class IDangerousService_Write_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "dangerous_write";
            public override string Description => "Dangerous write operation.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Reflection.MethodInfo GetTargetMethod()
            {
                var serviceType = typeof(global::Sample.IDangerousService);
                var paramTypes = new global::System.Type[] { typeof(string), };
                return serviceType.GetMethod("Write", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, paramTypes, null)
                    ?? throw new global::System.InvalidOperationException("Could not locate target method global::Sample.IDangerousService.Write.");
            }

            private static readonly global::System.Collections.Generic.HashSet<string> s_schemaExcludedParameters = new()
            {
            };

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var inferenceOptions = new global::Microsoft.Extensions.AI.AIJsonSchemaCreateOptions
                {
                    IncludeParameter = static p => !s_schemaExcludedParameters.Contains(p.Name!),
                };
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateFunctionJsonSchema(
                    GetTargetMethod(), title: string.Empty, description: string.Empty, inferenceOptions: inferenceOptions);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return null;
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = global::Microsoft.Maui.AI.Attributes.AIToolContext.Helpers.RequireServices(arguments);
                var __service = __provider.GetRequiredService<global::Sample.IDangerousService>();
                var __arg_data = global::Microsoft.Maui.AI.Attributes.AIToolContext.Helpers.GetRequiredArg<string>(arguments, "data");
                __service.Write(__arg_data);
                return null;
            }
        }

    }
}
